import { Inter } from "next/font/google";
import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'
import "./globals.css";

const chivo = Chivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-chivo',
})
const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Portafolio | Oscar M Alvarez G",
  description: "Generated by create next app",
  keywords:"Hola",
  author:"Oscar M Alvarez G"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta property="og:title" content="Portafolio - Oscar M Alvarez G" />
      <meta property="og:description" content="Descripción corta sobre ti o tus servicios" />
      <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
      <body className={chivo.variable + rubik.variable}>{children}</body>
    </html>
  );
}
